### ISSUE TITLE
🌶Dark Mode 探测方式

### ISSUE THREAD

**Issue by tomieric** [tomieric/tomieric.github.io#56]
by @Barret_China

### CSS

```css
@media
 (prefers-color-scheme: dark) {
  body {
    background-color: #000;
    color: white;
  }
}
```

### js

```js
window.matchMedia('(prefers-color-scheme: dark)').matches === true
```
