### ISSUE TITLE
[转] 一分钟 css 教程系列

### ISSUE THREAD

**Issue by tomieric** [tomieric/tomieric.github.io#63]
* [https://codyhouse.co/nuggets](https://codyhouse.co/nuggets)

## 表单按钮宽度自适应

使用弹性布局`(flexbox) `的`flex-direction`属性创建影响式按钮组布局

```html
<div class="btns">
  <button class="btn btn--subtle">Button</button>
  <button class="btn btn--primary">Button</button>
</div>
```

按钮组布局结构如上。

```scss
// 💡 CSS Nugget: From full-width to auto-width buttons using flex-direction
// ℹ️ Resize the window -> the buttons go from full-width to auto-width
// 🔗 https://codyhouse.co/nuggets/responsive-buttons-flex-direction

body {
  padding: 2em;
}

.btns {
  display: flex;
  flex-direction: column;
  margin-bottom: -0.5em;
  margin-left: -0.5em;

  .btn {
    margin-bottom: 0.5em;
    margin-left: 0.5em;
  }
}

@media (min-width: 32rem) {
  .btns {
    flex-direction: row;
  }
}
```

* [预览](https://codepen.io/codyhouse/pen/NWGLLxY)

## 同级兄弟元素滑过样式

使用`:not`选择器实现同级兄弟元素滑过样式

结构：

```html
<div>
  <div class="radio-btns" role="radiogroup">
    <div class="radio-btns__btn" role="radio" aria-checked="false" tabindex="-1" aria-label="Select image one">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/148866/cdn-36_img-1.jpg" alt="Image description">
    </div>

    <div class="radio-btns__btn" role="radio" aria-checked="false" tabindex="-1" aria-label="Select image two">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/148866/cdn-36_img-2.jpg" alt="Image description">
    </div>

    <div class="radio-btns__btn" role="radio" aria-checked="false" tabindex="-1" aria-label="Select image three">
      <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/148866/cdn-36_img-3.jpg" alt="Image description">
    </div>
  </div>
</div>
```

样式：

```scss
// 💡 CSS Nugget: Styling siblings on hover
// ℹ️ Use the :not CSS selector to stylize siblings on hover
// 🔗 https://codyhouse.co/nuggets/styling-siblings-on-hover

.radio-btns {
  display: grid;
  gap: 4px;
  grid-template-columns: repeat(3, 100px);

  &:hover .radio-btns__btn:not(:hover) {
    filter: grayscale(100%);

    &::after {
      background-color: rgba(#000, 0.5);
    }
  }
  
  @media (min-width: 30rem) {
    grid-template-columns: repeat(3, 150px);
  }
}

.radio-btns__btn {
  position: relative;
  cursor: pointer;
  transition: .3s;

  &::after {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(#000, 0);
    transition: .3s;
  }

  img {
    display: block;
    width: 100%;
    max-width: 100%;
  }
}

body {
  padding: 1em;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
}
```

* [预览](https://codepen.io/codyhouse/pen/KKdrmXj)

## flex gap属性实现间距平均排版

`flex-gap`属性未来会被浏览器支持，现可先使用变量参数方式实现

```scss
.stack {
  --gap: 0.5rem; /* 👈 gap control */
  display: flex;
  flex-wrap: wrap;
  margin-bottom: calc(-1 * var(--gap));
  margin-left: calc(-1 * var(--gap));
}

.stack > * {
  margin-bottom: var(--gap);
  margin-left: var(--gap);
}
```

* [预览](https://codepen.io/codyhouse/pen/bGVPpyg)

使用 `flex-gap`属性我们可以定义为

```css
.stack {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
}
```

## 链接下滑线滑过样式

现已对`text-decoration`css 属性增加了颜色及类型支持

* `text-decoration-color` 下划线颜色
* `text-decoration-style`  下划线类型样式

```scss
body {
  padding: 2em;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
}

.cool-link {
  color: indigo;
  text-decoration-color: hsla(275, 100%, 25%, 0.3);
  // text-decoration-style: wavy; // 🤟
  transition: .3s;

  &:hover {
    text-decoration-color: hsla(275, 100%, 25%, 1);
  }
}
```

* [预览](https://codepen.io/codyhouse/pen/gOPLWzq)

## favicon 暗黑模式

使用 `svg` 图标作为`favicon`的媒体，我们可以给 `svg` 文件增加样式，定义不用用户预览模式响应页面 `favicon` 颜色。

```html
<head>
  <!-- ...   -->

  <!-- favicon 👇 -->
  <link rel="icon" type="image/svg+xml" href="assets/img/favicon.svg">

  <!-- ...   -->
</head>
```

编辑`SVG`文件

```html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <style>
    path {
      fill: #212121; <!-- 明亮模式 -->
    }

    @media (prefers-color-scheme: dark) {
      path {
        fill: white; <!-- 暗黑模式 -->
        opacity: 0.5;
      }
    }
  </style>
  
  <path d="M24,13.2V10.8H20.191a10.6,10.6,0,0,0-.228-1.44A10.145,10.145,0,0,0,22.2,3H19.8a7.738,7.738,0,0,1-.939,3.706,6.873,6.873,0,0,0-2.9-2.516,4.121,4.121,0,0,0-7.926,0,6.892,6.892,0,0,0-2.9,2.516A7.748,7.748,0,0,1,4.2,3H1.8A10.145,10.145,0,0,0,4.037,9.36a10.6,10.6,0,0,0-.228,1.44H0v2.4H3.845a11.117,11.117,0,0,0,.279,1.326A10.156,10.156,0,0,0,1.8,21H4.2a7.732,7.732,0,0,1,.985-3.783C6.746,20.245,9.372,22.8,12,22.8s5.254-2.555,6.815-5.583A7.732,7.732,0,0,1,19.8,21h2.4a10.156,10.156,0,0,0-2.324-6.474,11.117,11.117,0,0,0,.279-1.326Zm-17.4-3a1.8,1.8,0,1,1,.527,1.273A1.8,1.8,0,0,1,6.6,10.2ZM12,18a2.4,2.4,0,1,1,1.7-.7A2.4,2.4,0,0,1,12,18Zm3.6-6a1.8,1.8,0,1,1,1.273-.527A1.8,1.8,0,0,1,15.6,12Z"/>
</svg>
```
